export const professionList = [
 "Web Development",
  "Graphic Design",
  "Digital Marketing",
  "Content Writing",
  "Photography",
  "Video Production",
  "SEO Services",
  "App Development",
  "Social Media Management",
  "UI/UX Design",
  "Copywriting",
  "E-commerce Solutions",
  "Consulting Services",
  "Event Planning",
  "Legal Services",
  "Financial Planning",
  "Fitness Training",
  "Language Translation",
  "Interior Design",
  "Virtual Assistance",
  "Carpentry",
  "Catering",
];
